// ignore_for_file: file_names

import 'dart:convert';

import 'package:file_selector/file_selector.dart';

/// Opens Compose DSL file-picker requests through Flutter's platform selector.
class ComposeDslFilePickerService {
  ComposeDslFilePickerService._();

  /// Opens one picker request serialized by the Rust Compose DSL host boundary.
  static Future<String> open(String requestJson) async {
    final request = _ComposeDslFilePickerRequest.fromJson(requestJson);
    if (request.picker == _ComposeDslFilePickerMode.directory) {
      final paths = request.allowMultiple
          ? await getDirectoryPaths()
          : await _openSingleDirectory();
      return _encodeResult(
        cancelled: paths.isEmpty,
        files: paths
            .whereType<String>()
            .map(_PickedFile.fromDirectory)
            .toList(growable: false),
      );
    }
    final typeGroups = _typeGroupsFor(request);
    final files = request.allowMultiple
        ? await openFiles(acceptedTypeGroups: typeGroups)
        : await _openSingleFile(typeGroups);
    final picked = await Future.wait(files.map(_PickedFile.fromXFile));
    return _encodeResult(cancelled: files.isEmpty, files: picked);
  }

  /// Builds the platform-neutral file-selector filter for one validated picker mode.
  static List<XTypeGroup> _typeGroupsFor(_ComposeDslFilePickerRequest request) {
    if (request.mimeTypes.isNotEmpty) {
      return <XTypeGroup>[
        XTypeGroup(
          label: 'Files',
          mimeTypes: request.mimeTypes,
          webWildCards: request.mimeTypes,
        ),
      ];
    }
    return switch (request.picker) {
      _ComposeDslFilePickerMode.document => const <XTypeGroup>[],
      _ComposeDslFilePickerMode.photo => <XTypeGroup>[_photoTypeGroup],
      _ComposeDslFilePickerMode.video => <XTypeGroup>[_videoTypeGroup],
      _ComposeDslFilePickerMode.media => <XTypeGroup>[_mediaTypeGroup],
      _ComposeDslFilePickerMode.directory => throw StateError(
        'Directories do not use file filters',
      ),
    };
  }

  /// Opens one directory and represents cancellation as an empty selection.
  static Future<List<String>> _openSingleDirectory() async {
    final path = await getDirectoryPath();
    return path == null ? const <String>[] : <String>[path];
  }

  /// Opens the single-file selector and normalizes a cancellation to an empty list.
  static Future<List<XFile>> _openSingleFile(
    List<XTypeGroup> typeGroups,
  ) async {
    final file = await openFile(acceptedTypeGroups: typeGroups);
    return file == null ? const <XFile>[] : <XFile>[file];
  }

  /// Serializes the host-independent picker result returned to Compose DSL JavaScript.
  static String _encodeResult({
    required bool cancelled,
    required List<_PickedFile> files,
  }) {
    return jsonEncode(<String, Object?>{
      'cancelled': cancelled,
      'files': files.map((file) => file.toJson()).toList(growable: false),
    });
  }
}

/// Enumerates the cross-platform picker modes accepted by the Rust host boundary.
enum _ComposeDslFilePickerMode { document, photo, video, media, directory }

const XTypeGroup _photoTypeGroup = XTypeGroup(
  label: 'Photos',
  extensions: <String>[
    'jpg',
    'jpeg',
    'png',
    'gif',
    'webp',
    'heic',
    'heif',
    'bmp',
    'tif',
    'tiff',
  ],
  mimeTypes: <String>['image/*'],
  uniformTypeIdentifiers: <String>['public.image'],
  webWildCards: <String>['image/*'],
);

const XTypeGroup _videoTypeGroup = XTypeGroup(
  label: 'Videos',
  extensions: <String>['mp4', 'mov', 'm4v', 'avi', 'mkv', 'webm', '3gp'],
  mimeTypes: <String>['video/*'],
  uniformTypeIdentifiers: <String>['public.movie'],
  webWildCards: <String>['video/*'],
);

const XTypeGroup _mediaTypeGroup = XTypeGroup(
  label: 'Photos and videos',
  extensions: <String>[
    'jpg',
    'jpeg',
    'png',
    'gif',
    'webp',
    'heic',
    'heif',
    'bmp',
    'tif',
    'tiff',
    'mp4',
    'mov',
    'm4v',
    'avi',
    'mkv',
    'webm',
    '3gp',
  ],
  mimeTypes: <String>['image/*', 'video/*'],
  uniformTypeIdentifiers: <String>['public.image', 'public.movie'],
  webWildCards: <String>['image/*', 'video/*'],
);

/// Stores the fully validated, platform-neutral picker request.
class _ComposeDslFilePickerRequest {
  const _ComposeDslFilePickerRequest({
    required this.picker,
    required this.allowMultiple,
    required this.mimeTypes,
  });

  final _ComposeDslFilePickerMode picker;
  final bool allowMultiple;
  final List<String> mimeTypes;

  /// Decodes the request generated by the Rust Compose DSL host API.
  factory _ComposeDslFilePickerRequest.fromJson(String rawJson) {
    final decoded = jsonDecode(rawJson);
    if (decoded is! Map<String, dynamic>) {
      throw const FormatException(
        'Compose DSL file picker request must be an object',
      );
    }
    final pickerToken = decoded['picker'];
    if (pickerToken is! String) {
      throw const FormatException(
        'Compose DSL file picker picker must be a string',
      );
    }
    final picker = switch (pickerToken) {
      'document' => _ComposeDslFilePickerMode.document,
      'photo' || 'image' => _ComposeDslFilePickerMode.photo,
      'video' => _ComposeDslFilePickerMode.video,
      'media' => _ComposeDslFilePickerMode.media,
      'directory' => _ComposeDslFilePickerMode.directory,
      _ => throw FormatException(
        'Unsupported Compose DSL file picker mode: $pickerToken',
      ),
    };
    final allowMultiple = decoded['allowMultiple'];
    if (allowMultiple is! bool) {
      throw const FormatException(
        'Compose DSL file picker allowMultiple is missing or invalid',
      );
    }
    return _ComposeDslFilePickerRequest(
      picker: picker,
      allowMultiple: allowMultiple,
      mimeTypes: (decoded['mimeTypes'] as List<dynamic>).cast<String>(),
    );
  }
}

/// Stores one selected item using the stable public Compose DSL result shape.
class _PickedFile {
  const _PickedFile({
    required this.uri,
    required this.path,
    required this.name,
    required this.mimeType,
    required this.size,
  });

  final String uri;
  final String path;
  final String name;
  final String? mimeType;
  final int size;

  /// Builds a directory result without attempting to read it as a file.
  factory _PickedFile.fromDirectory(String path) {
    final parsed = Uri.parse(path);
    final uri = parsed.scheme == 'content' ? parsed : Uri.directory(path);
    final segments = uri.pathSegments
        .where((segment) => segment.isNotEmpty)
        .toList();
    return _PickedFile(
      uri: uri.toString(),
      path: path,
      name: segments.isEmpty ? path : segments.last,
      mimeType: null,
      size: 0,
    );
  }

  /// Builds one public result entry from a file_selector result.
  static Future<_PickedFile> fromXFile(XFile file) async {
    final path = file.path;
    final parsedPath = Uri.tryParse(path);
    return _PickedFile(
      uri: parsedPath?.scheme == 'blob'
          ? parsedPath.toString()
          : Uri.file(path).toString(),
      path: path,
      name: file.name,
      mimeType: file.mimeType,
      size: await file.length(),
    );
  }

  /// Converts one selected item to the public Compose DSL JSON shape.
  Map<String, Object?> toJson() {
    return <String, Object?>{
      'uri': uri,
      'path': path,
      'name': name,
      'mimeType': mimeType,
      'size': size,
    };
  }
}
