//! Canonical bindings from JavaScript Tools methods to built-in tool contracts.

use super::tool_types::BuiltinToolName;

/// Binds one public Tools namespace method to its built-in executor contract.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct JsToolBinding {
    /// Contains the dotted JavaScript namespace path.
    pub namespace: &'static str,
    /// Contains the public method name inside the namespace.
    pub method: &'static str,
    /// Selects the exact built-in executor invoked by the method.
    pub tool: BuiltinToolName,
}

/// Declares one versioned JavaScript Tools method implementation.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct JsToolApiVariant {
    /// Contains the JavaScript namespace containing the gated method.
    pub namespace: &'static str,
    /// Contains the public method name controlled by the gate.
    pub method: &'static str,
    /// Contains the ToolPkg API version that selects this implementation.
    pub since: &'static str,
    /// Contains the exclusive upper ToolPkg API version for this implementation.
    pub until: Option<&'static str>,
    /// Contains an optional variant-specific JavaScript parameter list.
    pub arguments: Option<&'static [&'static str]>,
}

/// Contains every active JavaScript Tools method binding.
#[rustfmt::skip]
pub const JS_TOOL_BINDINGS: &[JsToolBinding] = &[
    JsToolBinding { namespace: "Chat", method: "agentStatus", tool: BuiltinToolName::AgentStatus },
    JsToolBinding { namespace: "Chat", method: "createNew", tool: BuiltinToolName::CreateNewChat },
    JsToolBinding { namespace: "Chat", method: "deleteChat", tool: BuiltinToolName::DeleteChat },
    JsToolBinding { namespace: "Chat", method: "findChat", tool: BuiltinToolName::FindChat },
    JsToolBinding { namespace: "Chat", method: "getMessages", tool: BuiltinToolName::GetChatMessages },
    JsToolBinding { namespace: "Chat", method: "getMessagesRange", tool: BuiltinToolName::GetChatMessagesRange },
    JsToolBinding { namespace: "Chat", method: "call", tool: BuiltinToolName::CallChatModel },
    JsToolBinding { namespace: "Chat", method: "listAll", tool: BuiltinToolName::ListChats },
    JsToolBinding { namespace: "Chat", method: "listCharacterCards", tool: BuiltinToolName::ListCharacterCards },
    JsToolBinding { namespace: "Chat", method: "listChats", tool: BuiltinToolName::ListChats },
    JsToolBinding { namespace: "Chat", method: "sendMessage", tool: BuiltinToolName::SendMessageToAi },
    JsToolBinding { namespace: "Chat", method: "sendMessageStreaming", tool: BuiltinToolName::SendMessageToAiStreaming },
    JsToolBinding { namespace: "Chat", method: "startService", tool: BuiltinToolName::StartChatService },
    JsToolBinding { namespace: "Chat", method: "stopService", tool: BuiltinToolName::StopChatService },
    JsToolBinding { namespace: "Chat", method: "switchTo", tool: BuiltinToolName::SwitchChat },
    JsToolBinding { namespace: "Chat", method: "updateTitle", tool: BuiltinToolName::UpdateChatTitle },
    JsToolBinding { namespace: "Files", method: "apply", tool: BuiltinToolName::ApplyFile },
    JsToolBinding { namespace: "Files", method: "copy", tool: BuiltinToolName::CopyFile },
    JsToolBinding { namespace: "Files", method: "create", tool: BuiltinToolName::CreateFile },
    JsToolBinding { namespace: "Files", method: "deleteFile", tool: BuiltinToolName::DeleteFile },
    JsToolBinding { namespace: "Files", method: "download", tool: BuiltinToolName::DownloadFile },
    JsToolBinding { namespace: "Files", method: "edit", tool: BuiltinToolName::EditFile },
    JsToolBinding { namespace: "Files", method: "exists", tool: BuiltinToolName::FileExists },
    JsToolBinding { namespace: "Files", method: "find", tool: BuiltinToolName::FindFiles },
    JsToolBinding { namespace: "Files", method: "grep", tool: BuiltinToolName::GrepCode },
    JsToolBinding { namespace: "Files", method: "grepContext", tool: BuiltinToolName::GrepContext },
    JsToolBinding { namespace: "Files", method: "info", tool: BuiltinToolName::FileInfo },
    JsToolBinding { namespace: "Files", method: "list", tool: BuiltinToolName::ListFiles },
    JsToolBinding { namespace: "Files", method: "mkdir", tool: BuiltinToolName::MakeDirectory },
    JsToolBinding { namespace: "Files", method: "move", tool: BuiltinToolName::MoveFile },
    JsToolBinding { namespace: "Files", method: "open", tool: BuiltinToolName::OpenFile },
    JsToolBinding { namespace: "Files", method: "read", tool: BuiltinToolName::ReadFileFull },
    JsToolBinding { namespace: "Files", method: "readBinary", tool: BuiltinToolName::ReadFileBinary },
    JsToolBinding { namespace: "Files", method: "readPart", tool: BuiltinToolName::ReadFilePart },
    JsToolBinding { namespace: "Files", method: "share", tool: BuiltinToolName::ShareFile },
    JsToolBinding { namespace: "Files", method: "unzip", tool: BuiltinToolName::UnzipFiles },
    JsToolBinding { namespace: "Files", method: "write", tool: BuiltinToolName::WriteFile },
    JsToolBinding { namespace: "Files", method: "writeBinary", tool: BuiltinToolName::WriteFileBinary },
    JsToolBinding { namespace: "Files", method: "zip", tool: BuiltinToolName::ZipFiles },
    JsToolBinding { namespace: "Memory", method: "create", tool: BuiltinToolName::CreateMemory },
    JsToolBinding { namespace: "Memory", method: "deleteLink", tool: BuiltinToolName::DeleteMemoryLink },
    JsToolBinding { namespace: "Memory", method: "deleteMemory", tool: BuiltinToolName::DeleteMemory },
    JsToolBinding { namespace: "Memory", method: "getByTitle", tool: BuiltinToolName::GetMemoryByTitle },
    JsToolBinding { namespace: "Memory", method: "link", tool: BuiltinToolName::LinkMemories },
    JsToolBinding { namespace: "Memory", method: "move", tool: BuiltinToolName::MoveMemory },
    JsToolBinding { namespace: "Memory", method: "query", tool: BuiltinToolName::QueryMemory },
    JsToolBinding { namespace: "Memory", method: "queryLinks", tool: BuiltinToolName::QueryMemoryLinks },
    JsToolBinding { namespace: "Memory", method: "update", tool: BuiltinToolName::UpdateMemory },
    JsToolBinding { namespace: "Memory", method: "updateLink", tool: BuiltinToolName::UpdateMemoryLink },
    JsToolBinding { namespace: "Memory", method: "updateUserPreferences", tool: BuiltinToolName::UpdateUserPreferences },
    JsToolBinding { namespace: "Net", method: "browserClick", tool: BuiltinToolName::BrowserClick },
    JsToolBinding { namespace: "Net", method: "browserClose", tool: BuiltinToolName::BrowserClose },
    JsToolBinding { namespace: "Net", method: "browserCloseAll", tool: BuiltinToolName::BrowserCloseAll },
    JsToolBinding { namespace: "Net", method: "browserConsoleMessages", tool: BuiltinToolName::BrowserConsoleMessages },
    JsToolBinding { namespace: "Net", method: "browserDrag", tool: BuiltinToolName::BrowserDrag },
    JsToolBinding { namespace: "Net", method: "browserEvaluate", tool: BuiltinToolName::BrowserEvaluate },
    JsToolBinding { namespace: "Net", method: "browserFileUpload", tool: BuiltinToolName::BrowserFileUpload },
    JsToolBinding { namespace: "Net", method: "browserFillForm", tool: BuiltinToolName::BrowserFillForm },
    JsToolBinding { namespace: "Net", method: "browserHandleDialog", tool: BuiltinToolName::BrowserHandleDialog },
    JsToolBinding { namespace: "Net", method: "browserHover", tool: BuiltinToolName::BrowserHover },
    JsToolBinding { namespace: "Net", method: "browserNavigate", tool: BuiltinToolName::BrowserNavigate },
    JsToolBinding { namespace: "Net", method: "browserNavigateBack", tool: BuiltinToolName::BrowserNavigateBack },
    JsToolBinding { namespace: "Net", method: "browserNetworkRequests", tool: BuiltinToolName::BrowserNetworkRequests },
    JsToolBinding { namespace: "Net", method: "browserPressKey", tool: BuiltinToolName::BrowserPressKey },
    JsToolBinding { namespace: "Net", method: "browserResize", tool: BuiltinToolName::BrowserResize },
    JsToolBinding { namespace: "Net", method: "browserRunCode", tool: BuiltinToolName::BrowserRunCode },
    JsToolBinding { namespace: "Net", method: "browserSelectOption", tool: BuiltinToolName::BrowserSelectOption },
    JsToolBinding { namespace: "Net", method: "browserSnapshot", tool: BuiltinToolName::BrowserSnapshot },
    JsToolBinding { namespace: "Net", method: "browserTabs", tool: BuiltinToolName::BrowserTabs },
    JsToolBinding { namespace: "Net", method: "browserTakeScreenshot", tool: BuiltinToolName::BrowserTakeScreenshot },
    JsToolBinding { namespace: "Net", method: "browserType", tool: BuiltinToolName::BrowserType },
    JsToolBinding { namespace: "Net", method: "browserWaitFor", tool: BuiltinToolName::BrowserWaitFor },
    JsToolBinding { namespace: "Net", method: "http", tool: BuiltinToolName::HttpRequest },
    JsToolBinding { namespace: "Net", method: "httpGet", tool: BuiltinToolName::HttpRequest },
    JsToolBinding { namespace: "Net", method: "httpPost", tool: BuiltinToolName::HttpRequest },
    JsToolBinding { namespace: "Net", method: "uploadFile", tool: BuiltinToolName::MultipartRequest },
    JsToolBinding { namespace: "Net", method: "visit", tool: BuiltinToolName::VisitWeb },
    JsToolBinding { namespace: "Net.cookies", method: "clear", tool: BuiltinToolName::ManageCookies },
    JsToolBinding { namespace: "Net.cookies", method: "get", tool: BuiltinToolName::ManageCookies },
    JsToolBinding { namespace: "Net.cookies", method: "set", tool: BuiltinToolName::ManageCookies },
    JsToolBinding { namespace: "SoftwareSettings", method: "exec", tool: BuiltinToolName::ExecuteCliCommand },
    JsToolBinding { namespace: "SoftwareSettings", method: "readEnvironmentVariable", tool: BuiltinToolName::ReadEnvironmentVariable },
    JsToolBinding { namespace: "SoftwareSettings", method: "writeEnvironmentVariable", tool: BuiltinToolName::WriteEnvironmentVariable },
    JsToolBinding { namespace: "System", method: "getAppUsageTime", tool: BuiltinToolName::GetAppUsageTime },
    JsToolBinding { namespace: "System", method: "getDeviceInfo", tool: BuiltinToolName::DeviceInfo },
    JsToolBinding { namespace: "System", method: "getLocation", tool: BuiltinToolName::GetDeviceLocation },
    JsToolBinding { namespace: "System", method: "getNotifications", tool: BuiltinToolName::GetNotifications },
    JsToolBinding { namespace: "System", method: "getSetting", tool: BuiltinToolName::GetSystemSetting },
    JsToolBinding { namespace: "System", method: "installApp", tool: BuiltinToolName::InstallApp },
    JsToolBinding { namespace: "System", method: "listApps", tool: BuiltinToolName::ListInstalledApps },
    JsToolBinding { namespace: "System", method: "sendNotification", tool: BuiltinToolName::SendNotification },
    JsToolBinding { namespace: "System", method: "setSetting", tool: BuiltinToolName::ModifySystemSetting },
    JsToolBinding { namespace: "System", method: "sleep", tool: BuiltinToolName::Sleep },
    JsToolBinding { namespace: "System", method: "startApp", tool: BuiltinToolName::StartApp },
    JsToolBinding { namespace: "System", method: "stopApp", tool: BuiltinToolName::StopApp },
    JsToolBinding { namespace: "System", method: "toast", tool: BuiltinToolName::Toast },
    JsToolBinding { namespace: "System", method: "uninstallApp", tool: BuiltinToolName::UninstallApp },
    JsToolBinding { namespace: "System", method: "usePackage", tool: BuiltinToolName::UsePackage },
    JsToolBinding { namespace: "System.bluetooth", method: "accept", tool: BuiltinToolName::BluetoothAccept },
    JsToolBinding { namespace: "System.bluetooth", method: "close", tool: BuiltinToolName::BluetoothClose },
    JsToolBinding { namespace: "System.bluetooth", method: "connect", tool: BuiltinToolName::BluetoothConnect },
    JsToolBinding { namespace: "System.bluetooth", method: "getState", tool: BuiltinToolName::GetBluetoothState },
    JsToolBinding { namespace: "System.bluetooth", method: "listBondedDevices", tool: BuiltinToolName::ListBluetoothBondedDevices },
    JsToolBinding { namespace: "System.bluetooth", method: "listen", tool: BuiltinToolName::BluetoothListen },
    JsToolBinding { namespace: "System.bluetooth", method: "read", tool: BuiltinToolName::BluetoothRead },
    JsToolBinding { namespace: "System.bluetooth", method: "requestEnable", tool: BuiltinToolName::RequestEnableBluetooth },
    JsToolBinding { namespace: "System.bluetooth", method: "requestPermission", tool: BuiltinToolName::RequestBluetoothPermission },
    JsToolBinding { namespace: "System.bluetooth", method: "scan", tool: BuiltinToolName::ScanBluetoothDevices },
    JsToolBinding { namespace: "System.bluetooth", method: "send", tool: BuiltinToolName::BluetoothSend },
    JsToolBinding { namespace: "System.bluetooth", method: "sendAndRead", tool: BuiltinToolName::BluetoothSendAndRead },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "connect", tool: BuiltinToolName::BluetoothBleConnect },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "discoverServices", tool: BuiltinToolName::BluetoothBleDiscoverServices },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "readCharacteristic", tool: BuiltinToolName::BluetoothBleReadCharacteristic },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "readNotifications", tool: BuiltinToolName::BluetoothBleReadNotifications },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "subscribe", tool: BuiltinToolName::BluetoothBleSubscribeCharacteristic },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "writeAndReadCharacteristic", tool: BuiltinToolName::BluetoothBleWriteAndReadCharacteristic },
    JsToolBinding { namespace: "System.bluetooth.ble", method: "writeCharacteristic", tool: BuiltinToolName::BluetoothBleWriteCharacteristic },
    JsToolBinding { namespace: "System.music", method: "pause", tool: BuiltinToolName::MusicPause },
    JsToolBinding { namespace: "System.music", method: "play", tool: BuiltinToolName::MusicPlay },
    JsToolBinding { namespace: "System.music", method: "resume", tool: BuiltinToolName::MusicResume },
    JsToolBinding { namespace: "System.music", method: "seek", tool: BuiltinToolName::MusicSeek },
    JsToolBinding { namespace: "System.music", method: "setVolume", tool: BuiltinToolName::MusicSetVolume },
    JsToolBinding { namespace: "System.music", method: "status", tool: BuiltinToolName::MusicStatus },
    JsToolBinding { namespace: "System.music", method: "stop", tool: BuiltinToolName::MusicStop },
    JsToolBinding { namespace: "System.terminal", method: "close", tool: BuiltinToolName::CloseTerminalSession },
    JsToolBinding { namespace: "System.terminal", method: "create", tool: BuiltinToolName::CreateTerminalSession },
    JsToolBinding { namespace: "System.terminal", method: "exec", tool: BuiltinToolName::ExecuteInTerminalSession },
    JsToolBinding { namespace: "System.terminal", method: "execStreaming", tool: BuiltinToolName::ExecuteInTerminalSessionStreaming },
    JsToolBinding { namespace: "System.terminal", method: "hiddenExec", tool: BuiltinToolName::ExecuteHiddenTerminalCommand },
    JsToolBinding { namespace: "System.terminal", method: "info", tool: BuiltinToolName::GetTerminalInfo },
    JsToolBinding { namespace: "System.terminal", method: "input", tool: BuiltinToolName::InputInTerminalSession },
    JsToolBinding { namespace: "System.terminal", method: "screen", tool: BuiltinToolName::GetTerminalSessionScreen },
];

/// Contains every versioned implementation applied to generated Tools methods.
pub const JS_TOOL_API_VARIANTS: &[JsToolApiVariant] = &[JsToolApiVariant {
    namespace: "Chat",
    method: "call",
    since: "2.0.0",
    until: None,
    arguments: None,
}];
